# Workflow derived from https://github.com/r-lib/actions/tree/v2-branch/check-r-package
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - run: DISPLAY=:1.0
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
